package com.sj.gpsutil.tracking

data class AccelMetrics(
    val meanX: Float,
    val meanY: Float,
    val meanZ: Float,
    val meanVert: Float,
    val maxMagnitude: Float,
    val meanMagnitude: Float,
    val rms: Float,
    val peakRatio: Float,
    val stdDev: Float,
    val avgRms: Float,
    val avgMaxMagnitude: Float,
    val avgMeanMagnitude: Float,
    val avgStdDev: Float,
    val avgPeakRatio: Float,
    val roadQuality: String?,
    val featureDetected: String?,
    val rawData: List<FloatArray>,
    val fwdRms: Float = 0f,
    val fwdMax: Float = 0f,
    val fwdMean: Float = 0f,
    val latRms: Float = 0f,
    val latMax: Float = 0f,
    val latMean: Float = 0f,
    val signedFwdRms: Float = 0f,
    val signedLatRms: Float = 0f,
    val leanAngleDeg: Float = 0f,
    val deltaSpeed: Float = 0f,
    val deltaCourse: Float = 0f,
    val fwdValues: List<Float> = emptyList(),
    val latValues: List<Float> = emptyList()
)
